### ISSUE TITLE
Abundances

### ISSUE THREAD

**Issue by MariaTsantaki** [DanielAndreasen/MOOGme#10]
Actually this could be easy: 

0) Find a line list of element
Let's start with iron!
1) Set teff, logg, metal, vmic and interpolate the model.
2) Run MOOG (abfind.par)
3) Read output
Return the average abundance. 
Save output file
Apply Vardan's outlier removal suggestion

**Comment by DanielAndreasen** [comment]
Can you see this @elisadelgado ?

**Comment by elisadelgado** [comment]
Hi Daniel
I received this email, but I'm not sure if I see what you think I see :P

**Comment by DanielAndreasen** [comment]
I was just checking something on github. I guess it worked :cat:

**Comment by MariaTsantaki** [comment]
Better way of saving output.
Update GUI.

**Comment by DanielAndreasen** [comment]
Closed with commit eba63de82229be85cf3e9
