### ISSUE TITLE
Implement ARES in the GUI

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#11]
We can implement ARES as well. It is easy to write a wrapper as we do for MOOG. This is connected to issue #7 but this is the main issue thread.

**Comment by MariaTsantaki** [comment]
Mostly done. For full automation the user has to define the rejt parameter.

**Comment by MariaTsantaki** [comment]
The flag for plots works only for the first one in the GUI and then there is no command to continue.

**Comment by DanielAndreasen** [comment]
I think this is working.
