### ISSUE TITLE
Present results from abundance of many stars

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#18]
Any good ideas to how we can present the results from abundance analysis of more than 1 star.
Currently, we create a csv file (`abundances.csv`) which is nice, but it is cramped.
A tool like `preprocess.py` would be nice, but I don't know how we should present the data.

**Comment by DanielAndreasen** [comment]
In commit  52846d6 I print the csv file in the end in a relative nice way. This might look better in the terminal than the GUI.
Still need suggestions for ways to present the this data.

**Comment by MariaTsantaki** [comment]
We also could add an option for the user to select a specific element from the linelist.

**Comment by DanielAndreasen** [comment]
Or rather specific elements. But if we have a line list with a lot of different elements, why not just calculate the abundance for all? The user can extract what she needs from `abundances.csv` easily.

**Comment by MariaTsantaki** [comment]
OK. What about non-LTE corrections? We can talk with Elisa for that.

**Comment by DanielAndreasen** [comment]
Good point. Maybe we can close this issue and open a new issue on non-LTE corrections.
