### ISSUE TITLE
Warning when using normal optical linelist for cool stars

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#20]
For the EW driver, we could give the user a warning, if the effective temperature is low and the normal line list (optical) is used, instead of the one from Tsantaki et al. Since the latter is a subset of the former, we could just check for a few lines we knoe should only be in the "normal" line list.

**Comment by MariaTsantaki** [comment]
Yes. Also there should be a list of line lists to choose from including for chemical abundances (Adibakyan+ and Delgado-Mena+).

**Comment by DanielAndreasen** [comment]
This should be at temperatures lower than 5200K.

**Comment by MariaTsantaki** [comment]
The rawLinelist folder with the above linelists should be provided. I dont know how to create a folder in git. :(

**Comment by DanielAndreasen** [comment]
Yes, the line lists should be provided, but we need to document the different line lists we provide, so the right authors get credit if a user use a given line list. So let's wait a little before we put the different linelists online.

**Comment by DanielAndreasen** [comment]
This is fixed with the PR #32. Use it by setting `teffrange` in the `StarMe.cfg` file option part.
