### ISSUE TITLE
Use spectra for ARES and synth not in "spectra" folder

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#22]
It could be really nice for the user to use spectra for ARES and synthesis which is not in the `spectra` folder. If we just do some checks on the the filepath, it should be simple to implement.

**Comment by MariaTsantaki** [comment]
Agree. Actually we should remove the spectra folder.

**Comment by DanielAndreasen** [comment]
I don't think we should remove it for at least two reasons. First, this gives a nice structure. A person can do all spectroscopy within the MOOGme folder (we use the spectra for both ARES and synthesis in the future). Second, when creating the configuration file for ARES, it is easier to create this  
`linelist.ares spectrum.fits options`  
than this  
`linelist.ares /path/to/spectrum.fits options`

But the last option should be possible. But if the full path is not given, it should be assumed it is in the `spectra` folder.

**Comment by DanielAndreasen** [comment]
Commit 3b0d4ea0b2bf52 breaks the code. When I run the `aresDriver.py` after this commit I get errors. We need to redo this.

**Comment by MariaTsantaki** [comment]
OK I run it with no error
