### ISSUE TITLE
Clean output on ARES run

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#23]
At the moment the output from ARES is a bit messy, and not newlines between different runs.
Let's make it easier to read, and also print which spectra and linelist is used for all runs. Is this something for you @MariaTsantaki :smile:

**Comment by DanielAndreasen** [comment]
How about this commit  fd61f95? It doesn't always print all the stuff (only if it gives information), and the information is indented, and different runs are clearly seperated.

**Comment by MariaTsantaki** [comment]
Sorry I removed the indented stuff.  I added the option: 'output': False where the user can name the ares output. Then they are transformed to output+.moog format. 

To me the outputs look nice. Except some prints like rm: cannot remove `tmp': No such file or directory
But they come from ARES. 
Are you satisfied to close the issue?
commit 3b0d4ea

**Comment by DanielAndreasen** [comment]
I Maria. Let me test this later. It looks like nice additions. Would you be opposed to having the indented lines again?

Can you give a reference to where the `rm` fails. I can add a try/except around it.

Good job, this is almost ready to close.

**Comment by MariaTsantaki** [comment]
It is a problem or ARES either you run it inside MOOGme or not. 
Before it finishes, I get this message:
rm: cannot remove `tmp': No such file or directory
rm: cannot remove `tmp2': No such file or directory
rm: cannot remove `tmp3': No such file or directory
rm: cannot remove `tmp20': No such file or directory
rm: cannot remove `tmp22': No such file or directory
rm: cannot remove `tmp23': No such file or directory
int 2 status: 0
 FINISH. HAVE A GOOD DAY...

**Comment by MariaTsantaki** [comment]
I do not have any particular feeling about the indented lines. :)

**Comment by DanielAndreasen** [comment]
I do not understand where the `rm`error comes from. You get that if you run `ARES` by typing it in the terminal too? I have been very careful not to try remove stuff which is not there,

I'll put back the indentation of the lines.

**Comment by MariaTsantaki** [comment]
Yes, I have the version of ARES from the sergio's webpage. When plot=0, ARES removes stuff that are not there. These files are for the plotting.

**Comment by DanielAndreasen** [comment]
Okay, then we should ask Sérgio to fix his software :)

**Comment by DanielAndreasen** [comment]
@sousasag: There are problems with ARES. Can you read the thread above?

**Comment by DanielAndreasen** [comment]
Sérgio should fix this in ARES, but if it annoys you, you can remove all lines in areslib.h with something link `system("rm tmp")`.

**Comment by sousasag** [comment]
You can now use this version with this problem fixed:

https://github.com/sousasag/ARES
