### ISSUE TITLE
logg from LC not working

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#29]
The correction for logg we apply doesn't work right. When I switch in on in batch mode, it doesn't work, but sometimes it work in the GUI version, but I can't turn it off.

**Comment by MariaTsantaki** [comment]
I would prefer to put the correction for asteroseismology from the same paper. Do you agree to make that correction? I can sign for this task.

**Comment by DanielAndreasen** [comment]
Yes, that is fine by me, if that correction is better. We can maybe just add more columns in `results.csv` then let the user have it all.

**Comment by MariaTsantaki** [comment]
I added the astero option. Now when True moogme writes the results in the results.cvs otherwise it writes False.
