### ISSUE TITLE
Gooey free version of MOOGme

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#39]
Since there are quite a few problems with the installation of Gooey (when people don't want to use something like anaconda), maybe we should make a Gooey free version of `MOOGme.py`, where it is entirely called from the commandline.

**Comment by MariaTsantaki** [comment]
Yes. Even though they can still run very easy from command line for every driver.

**Comment by DanielAndreasen** [comment]
But since it is low-cost in development time, we might as well do it.
