### ISSUE TITLE
Model atmospheres for ODFNEW

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#4]
We can not fill in the gaps in the grid here with the previous grid. We need to interpolate our own grid.

**Comment by MariaTsantaki** [comment]
How we proceed on that? Should we give up on Kurucz and try to create MARCS grids for which the code is already provided?

**Comment by DanielAndreasen** [comment]
I'm not sure what to do. But I think circumstances dictates we need to provide MOOGme with MARCS models. The problem with the Kurucz grid is, that it's complicated to do ourselves. We need a special compiler, which cost a lot of money. And even with that, it doesn't really work that well (as far as Sérgio told me).

**Comment by MariaTsantaki** [comment]
Our metallicity grid is: feh: (-3.0, -2.5, -2.0, -1.5, -1.0, -0.5, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.5, 1.0). 
If we change to let's say an equally spaced: -3.0, +0.75, step=0.25, the only thing we have to change is the function that searches the 4 closest models, right?

**Comment by DanielAndreasen** [comment]
In principle we can make it thinner, but why do you want to do that? To save computation time and only look for 2x2x2 models instead of 4x2x2? We don't gain much there.

**Comment by MariaTsantaki** [comment]
Daniel can you check if the changes you made for the GetModels class are updated in the utils?

**Comment by DanielAndreasen** [comment]
Updated for what? I always push to github, so the latest version is online.

**Comment by MariaTsantaki** [comment]
yes. 
Funny.. I have a version that works and it is not the one pushed.. :P

**Comment by MariaTsantaki** [comment]
Nevermind.. my mistake..

**Comment by MariaTsantaki** [comment]
I think apogee_kurucz are added correctly. I renamed the folder /models/APOGEE_Kurucz to /models/apogee_kurucz .

**Comment by MariaTsantaki** [comment]
Does anyone know the best way to download marcs models? It is not that easy from their website..

**Comment by DanielAndreasen** [comment]
I'm trying from their web page (http://marcs.astro.uu.se), but you have to create an user. Sometimes it complains about the email, but try change your username instead.

**Comment by MariaTsantaki** [comment]
I got them manually. Not the most fun way. 
I will give it a try to convert to krz format.

**Comment by DanielAndreasen** [comment]
Impressive! That must have taken forever.
Let me know if I can help with something.
