### ISSUE TITLE
Bumping parameters

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#5]
When bumping parameters, we should only bump parameters which are not fixed, or return the previous value.
We could pass an `alpha` dependent on the fix, if this is 0 (i.e. the parameter is fixed), then don't change this parameter.

**Comment by MariaTsantaki** [comment]
Added flag for fixed parameters.. Solved

**Comment by DanielAndreasen** [comment]
Do you care to share? :cat:

**Comment by DanielAndreasen** [comment]
Fixed with commit 2fd501f5e8952df3c412
