### ISSUE TITLE
Configuration file for each driver

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/MOOGme#8]
Instead of having a `StarMe.cfg` file we should have something like `EW.cfg` for the EW driver, `synth.cfg` for the synthesis driver, and `abund.cfg` for the abundances driver. The drivers were introduced in commit bc0f0ee and a8f5c9b.

**Comment by DanielAndreasen** [comment]
For abundances, this is moved to issue #10

**Comment by DanielAndreasen** [comment]
Is this relevant anymore? At the moment we use the same configuration file for all (except ARES), namely `StarMe.cfg`. Is this optimal, or should we change it?

**Comment by MariaTsantaki** [comment]
Probably we should change for each Driver since each of them has different options.
